import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import DefaultLayout from "@/src/components/ui/layouts/defaultLayout/DefaultLayout";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/src/i18n/routing";
import ReactQueryProvider from "@/src/components/providers/ReactQueryProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ModalStoreProvider } from "@/src/components/providers/modalStoreProvider";
import { getCompanyDetailByKeyService } from "@/src/service/apiServices/companyDetail.service";
import { CompanyDetailEnum } from "@/src/utils/enums/CompanyDetail.enum";
import getImageSrcByBucketAndFileNames from "@/src/utils/functions/getImageSrcByBucketAndFileNames";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export async function generateMetadata() {
  const favicon = await getCompanyDetailByKeyService(CompanyDetailEnum.FAVICON);
  const metaTitle = await getCompanyDetailByKeyService(
    CompanyDetailEnum.HOME_META_TITLE,
  );
  const metaDescription = await getCompanyDetailByKeyService(
    CompanyDetailEnum.HOME_META_DESCRIPTION,
  );

  const metaData = {
    icons: {},
    title: "Create Next App",
    description: "Generated by create next app",
  };

  if (metaTitle?.value) {
    metaData.title = metaTitle.value;
  }

  if (metaDescription?.value) {
    metaData.description = metaDescription.value;
  }

  if (favicon?.image) {
    const faviconUrl = getImageSrcByBucketAndFileNames({
      bucketName: "commercor",
      fileName: favicon.image,
    });

    metaData.icons = {
      icon: faviconUrl,
      apple: faviconUrl,
    };
  }

  return metaData;
}

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#f0f2f5] antialiased`}
      >
        <AntdRegistry>
          <ReactQueryProvider>
            <ModalStoreProvider>
              <NextIntlClientProvider>
                <DefaultLayout>{children}</DefaultLayout>
              </NextIntlClientProvider>
            </ModalStoreProvider>
          </ReactQueryProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
