import { BadRequestException, Injectable } from '@nestjs/common'; import { DataSource, EntityManager } from 'typeorm';
import { LoyaltySettingsEntity } from '@/src/libs/models/entities/reward/LoyaltySettings.entity'; import { CustomerRewardAccountEntity } from '@/src/libs/models/entities/reward/CustomerRewardAccount.entity'; import { RewardTransactionEntity } from '@/src/libs/models/entities/reward/RewardTransaction.entity'; import { RewardTransactionType, RewardsGrantedOn } from '@/src/utils/enums/RewardEnums'; import { calculateEarnings, RewardSettings } from './reward-calculator';
const defaults: RewardSettings = { pointsEnabled:false, pointsPerCurrencyUnit:0, pointsPerCurrencyRedemptionUnit:100, minimumPointsToRedeem:0, maximumPointsRedemptionPercent:0, cashbackEnabled:false, cashbackPercent:0, cashbackMinimumOrderAmount:0, cashbackMaximumPerOrder:null, maximumCashbackUsePercent:0 };
@Injectable()
export class RewardsService {
  constructor(private readonly dataSource: DataSource) {}
  async settings(manager: EntityManager) { const r = await manager.getRepository(LoyaltySettingsEntity).findOne({where:{}}); return { ...defaults, ...(r || {}), pointsPerCurrencyUnit:Number(r?.pointsPerCurrencyUnit??0), pointsPerCurrencyRedemptionUnit:Number(r?.pointsPerCurrencyRedemptionUnit??100), maximumPointsRedemptionPercent:Number(r?.maximumPointsRedemptionPercent??0), cashbackPercent:Number(r?.cashbackPercent??0), cashbackMinimumOrderAmount:Number(r?.cashbackMinimumOrderAmount??0), cashbackMaximumPerOrder:r?.cashbackMaximumPerOrder==null?null:Number(r.cashbackMaximumPerOrder), maximumCashbackUsePercent:Number(r?.maximumCashbackUsePercent??0) }; }
  async account(manager: EntityManager, customerId: string, lock=false) { const repo=manager.getRepository(CustomerRewardAccountEntity); let a=await repo.findOne({where:{customerId},...(lock?{lock:{mode:'pessimistic_write' as const}}:{})}); if(!a){ try { a=await repo.save(repo.create({customerId,pointsBalance:0,cashbackBalance:0})); } catch { a=await repo.findOneOrFail({where:{customerId},...(lock?{lock:{mode:'pessimistic_write' as const}}:{})}); } } await this.expireRewards(manager,a); return a; }
  private async expireRewards(manager:EntityManager,a:CustomerRewardAccountEntity){const repo=manager.getRepository(RewardTransactionEntity);const rows=await repo.find({where:{customerId:a.customerId}});const now=Date.now();const active=rows.filter(r=>!r.description.startsWith('Expired reward balance'));
    const pointsTarget=Math.max(0,active.reduce((sum,r)=>sum+(r.pointsAmount&&r.pointsAmount>0&&r.expiresAt&&r.expiresAt.getTime()<=now?0:Number(r.pointsAmount||0)),0));
    const cashbackTarget=Math.max(0,Number(active.reduce((sum,r)=>sum+(Number(r.cashbackAmount||0)>0&&r.expiresAt&&r.expiresAt.getTime()<=now?0:Number(r.cashbackAmount||0)),0).toFixed(2)));
    const expiredPoints=Math.max(0,a.pointsBalance-pointsTarget);const expiredCashback=Math.max(0,Number((Number(a.cashbackBalance)-cashbackTarget).toFixed(2)));if(!expiredPoints&&!expiredCashback)return;
    a.pointsBalance-=expiredPoints;a.cashbackBalance=Number(a.cashbackBalance)-expiredCashback;await manager.getRepository(CustomerRewardAccountEntity).save(a);await repo.save(repo.create({customerId:a.customerId,orderId:null,paymentId:null,type:expiredPoints?RewardTransactionType.POINTS_REVERSAL:RewardTransactionType.CASHBACK_REVERSAL,pointsAmount:expiredPoints?-expiredPoints:null,cashbackAmount:expiredCashback?-expiredCashback:null,description:'Expired reward balance',expiresAt:null}));}
  async summary(customerId:string){ const a=await this.account(this.dataSource.manager,customerId); const s=await this.settings(this.dataSource.manager); const tx=await this.dataSource.getRepository(RewardTransactionEntity).find({where:{customerId},order:{created_at:'DESC'},take:20}); return {pointsBalance:a.pointsBalance,cashbackBalance:Number(a.cashbackBalance),pointsEnabled:s.pointsEnabled,cashbackEnabled:s.cashbackEnabled,recentTransactions:tx}; }
  async grant(manager:EntityManager, customerId:string, orderId:string, paymentId:string, eligibleSpend:number){ const raw=await manager.getRepository(LoyaltySettingsEntity).findOne({where:{}}); if(raw && raw.rewardsGrantedOn!==RewardsGrantedOn.COMPLETED)return; const s=await this.settings(manager); const earned=calculateEarnings(eligibleSpend,s); const repo=manager.getRepository(RewardTransactionEntity); const a=await this.account(manager,customerId,true); const expires=(days:number|null)=>days?new Date(Date.now()+days*86400000):null;
    if(earned.points && !(await repo.existsBy({orderId,type:RewardTransactionType.EARN_POINTS}))){a.pointsBalance+=earned.points;await repo.save(repo.create({customerId,orderId,paymentId,type:RewardTransactionType.EARN_POINTS,pointsAmount:earned.points,cashbackAmount:null,description:'Points earned from completed order',expiresAt:expires(raw?.pointsExpirationDays??null)}));}
    if(earned.cashback && !(await repo.existsBy({orderId,type:RewardTransactionType.EARN_CASHBACK}))){a.cashbackBalance=Number(a.cashbackBalance)+earned.cashback;await repo.save(repo.create({customerId,orderId,paymentId,type:RewardTransactionType.EARN_CASHBACK,pointsAmount:null,cashbackAmount:earned.cashback,description:'Cashback earned from completed order',expiresAt:expires(raw?.cashbackExpirationDays??null)}));}
    await manager.getRepository(CustomerRewardAccountEntity).save(a);
  }
  async redeem(manager:EntityManager, customerId:string, orderId:string, paymentId:string, points:number, pointsDiscount:number, cashback:number){ const a=await this.account(manager,customerId,true); if(a.pointsBalance<points)this.bad('Insufficient points balance.'); if(Number(a.cashbackBalance)<cashback)this.bad('Insufficient cashback balance.'); const repo=manager.getRepository(RewardTransactionEntity);
    if(points){a.pointsBalance-=points;await repo.save(repo.create({customerId,orderId,paymentId,type:RewardTransactionType.REDEEM_POINTS,pointsAmount:-points,cashbackAmount:null,description:`Redeemed for ${pointsDiscount.toFixed(2)} order discount`,expiresAt:null}));}
    if(cashback){a.cashbackBalance=Number(a.cashbackBalance)-cashback;await repo.save(repo.create({customerId,orderId,paymentId,type:RewardTransactionType.USE_CASHBACK,pointsAmount:null,cashbackAmount:-cashback,description:'Cashback used on order',expiresAt:null}));}
    if(a.pointsBalance<0||Number(a.cashbackBalance)<0)this.bad('Reward balance cannot become negative.'); await manager.getRepository(CustomerRewardAccountEntity).save(a);
  }
  async restoreRedemption(manager:EntityManager,customerId:string,orderId:string,paymentId:string,points:number,cashback:number,description:string){if(!points&&!cashback)return;const ledger=manager.getRepository(RewardTransactionEntity);if(await ledger.existsBy({orderId,type:RewardTransactionType.ADMIN_ADJUSTMENT}))return;const a=await this.account(manager,customerId,true);a.pointsBalance+=points;a.cashbackBalance=Number(a.cashbackBalance)+cashback;await manager.getRepository(CustomerRewardAccountEntity).save(a);await ledger.save(ledger.create({customerId,orderId,paymentId,type:RewardTransactionType.ADMIN_ADJUSTMENT,pointsAmount:points||null,cashbackAmount:cashback||null,description,expiresAt:null}));}
  bad(message:string):never{throw new BadRequestException(message);}
}
