import {
  AppstoreOutlined,
  BarcodeOutlined,
  ContainerOutlined,
  FileTextOutlined,
  FilterOutlined,
  GiftOutlined,
  InboxOutlined,
  LineChartOutlined,
  MessageOutlined,
  PercentageOutlined,
  ShoppingCartOutlined,
  ShopOutlined,
  SolutionOutlined,
  TagsOutlined,
  TeamOutlined,
  UserOutlined,
  SettingOutlined,
  DollarOutlined,
  DashboardOutlined,
} from "@ant-design/icons";
import { UserRoleEnum } from "../../../../../utils/enums/UserEnums.ts";

export default [
  {
    key: "dashboard",
    icon: <DashboardOutlined />,
    label: "Dashboard",
    path: "/admin",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "analytics",
    icon: <LineChartOutlined />,
    label: "Analytics",
    path: "/admin/analytics",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "customers",
    icon: <TeamOutlined />,
    label: "Customers",
    path: "/admin/customers",
    roles: [UserRoleEnum.ADMIN, UserRoleEnum.COMPANY],
  },
  {
    key: "company",
    icon: <ShopOutlined />,
    label: "Company",
    path: "/admin/companies",
    roles: [UserRoleEnum.ADMIN, UserRoleEnum.COMPANY],
  },
  {
    key: "categories",
    icon: <AppstoreOutlined />,
    label: "Categories",
    path: "/admin/categories",
    roles: [
      UserRoleEnum.ADMIN,
      UserRoleEnum.COMPANY,
      UserRoleEnum.STOCK_MANAGER,
    ],
  },
  {
    key: "brands",
    icon: <TagsOutlined />,
    label: "Brands",
    path: "/admin/brands",
    roles: [
      UserRoleEnum.ADMIN,
      UserRoleEnum.COMPANY,
      UserRoleEnum.STOCK_MANAGER,
    ],
  },
  {
    key: "products",
    icon: <InboxOutlined />,
    label: "Products",
    path: "/admin/products",
    roles: [
      UserRoleEnum.ADMIN,
      UserRoleEnum.COMPANY,
      UserRoleEnum.STOCK_MANAGER,
    ],
  },
  {
    key: "product-filters",
    icon: <FilterOutlined />,
    label: "Product Filters",
    path: "/admin/product-filters",
    roles: [
      UserRoleEnum.ADMIN,
      UserRoleEnum.COMPANY,
      UserRoleEnum.STOCK_MANAGER,
    ],
  },
  {
    key: "orders",
    icon: <ShoppingCartOutlined />,
    label: "Orders",
    path: "/admin/orders",
    roles: [UserRoleEnum.ADMIN, UserRoleEnum.SALES, UserRoleEnum.COMPANY],
  },
  {
    key: "users",
    icon: <UserOutlined />,
    label: "Users",
    path: "/admin/users",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "commerce-settings",
    icon: <DollarOutlined />,
    label: "Shipping & Tax",
    path: "/admin/commerce-settings",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "loyalty-settings",
    icon: <GiftOutlined />,
    label: "Loyalty & Cashback",
    path: "/admin/loyalty-settings",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "coupons",
    icon: <BarcodeOutlined />,
    label: "Coupons",
    path: "/admin/coupons",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "promotions",
    icon: <PercentageOutlined />,
    label: "Promotions",
    path: "/admin/promotions",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "reviews",
    icon: <MessageOutlined />,
    label: "Reviews",
    path: "/admin/reviews",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "invoices",
    icon: <FileTextOutlined />,
    label: "Invoices",
    path: "/admin/invoices",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "inventory",
    icon: <ContainerOutlined />,
    label: "Inventory",
    path: "/admin/inventory",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "abandoned-carts",
    icon: <SolutionOutlined />,
    label: "Abandoned Carts",
    path: "/admin/abandoned-carts",
    roles: [UserRoleEnum.ADMIN],
  },
  {
    key: "settings",
    icon: <SettingOutlined />,
    label: "Store Settings",
    path: "/admin/settings",
    roles: [UserRoleEnum.ADMIN, UserRoleEnum.COMPANY],
  },
];
