import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Schema generated by the original Commercor entities at commit 99980c1.
 * This is deliberately the state immediately before AddProductFilterCategories.
 */
export class InitialSchema1786224000000 implements MigrationInterface {
  name = 'InitialSchema1786224000000';

  private readonly coreTables = [
    'users',
    'product_filter_option_translations',
    'product_filter_options',
    'product_filters',
    'product_filter_translations',
    'product_images',
    'brand_translations',
    'brands',
    'category_translations',
    'categories',
    'products',
    'product_translations',
    'product_filter_option_values',
    'payments',
    'customers',
    'addresses',
    'orders',
    'order_items',
    'company_users',
    'company_details',
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    const existence = await Promise.all(
      this.coreTables.map((table) => queryRunner.hasTable(table)),
    );
    if (existence.every(Boolean)) return;
    if (existence.some(Boolean)) {
      const missing = this.coreTables.filter((_, index) => !existence[index]);
      throw new Error(
        `Refusing to apply InitialSchema to a partial legacy schema. Missing: ${missing.join(', ')}`,
      );
    }

    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
    const statements = [
      `CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "username" character varying NOT NULL, "email" character varying, "password" character varying NOT NULL, "role" character varying NOT NULL, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
      `CREATE TABLE "product_filter_option_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productFilterOptionId" uuid NOT NULL, "lang" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8bb7d107ce3ad49cfe6753ef1e4" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "IDX_2ae7a08357a785f8df893f76e6" ON "product_filter_option_translations" ("name") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "product_filter_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productFilterId" uuid NOT NULL, CONSTRAINT "PK_4ca9c7ab904ec0bbce33f6c7260" PRIMARY KEY ("id"))`,
      `CREATE TABLE "product_filters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "type" character varying NOT NULL, CONSTRAINT "PK_14ea310a31a40fc423c23ba0116" PRIMARY KEY ("id"))`,
      `CREATE TABLE "product_filter_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productFilterId" uuid NOT NULL, "lang" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_e420d0d809aedf96401a042d4ad" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "IDX_6cff2edc6473d2da6691b832a0" ON "product_filter_translations" ("name") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "IDX_bf9b33384191e57c72daec2c66" ON "product_images" ("name") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "brand_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "brandId" uuid NOT NULL, "lang" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "slug" character varying NOT NULL, "metaTitle" character varying NOT NULL, "metaDescription" character varying NOT NULL, CONSTRAINT "PK_cea5b0039a8925041c380ee1302" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "unique_slug_not_deleted" ON "brand_translations" ("slug") WHERE "deleted_at" IS NULL`,
      `CREATE UNIQUE INDEX "unique_name_not_deleted" ON "brand_translations" ("name") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "rank" integer NOT NULL, "image" character varying, CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`,
      `CREATE TABLE "category_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "categoryId" uuid NOT NULL, "lang" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "slug" character varying NOT NULL, "metaTitle" character varying NOT NULL, "metaDescription" character varying NOT NULL, CONSTRAINT "UQ_1751db555e149ae23a900708fc4" UNIQUE ("slug"), CONSTRAINT "PK_9dff018a4a26a924c60d3e86432" PRIMARY KEY ("id"))`,
      `CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "parentId" character varying, "image" character varying, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`,
      `CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "price" numeric(10,2) NOT NULL, "stock" integer NOT NULL, "brandId" uuid, "categoryId" uuid, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`,
      `CREATE TABLE "product_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productId" uuid NOT NULL, "lang" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "slug" character varying NOT NULL, "metaTitle" character varying NOT NULL, "metaDescription" character varying NOT NULL, CONSTRAINT "PK_38feaa5884a6a0171d067cc9d15" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "IDX_a46e7ec38cbee8fc0f960c6b03" ON "product_translations" ("slug") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "product_filter_option_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productFilterId" character varying NOT NULL, "productFilterOptionId" character varying NOT NULL, "productId" character varying NOT NULL, CONSTRAINT "PK_0faf3c6f157567d848d991510bf" PRIMARY KEY ("id"))`,
      `CREATE INDEX "IDX_53b57ac72b404ff1ee091865cd" ON "product_filter_option_values" ("productId")`,
      `CREATE UNIQUE INDEX "unique_product_filter_value" ON "product_filter_option_values" ("productFilterOptionId", "productId")`,
      `CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "totalAmount" integer NOT NULL, "refundedAmount" integer NOT NULL, "status" character varying NOT NULL, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`,
      `CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "unique_email_not_deleted" ON "customers" ("email") WHERE "deleted_at" IS NULL`,
      `CREATE UNIQUE INDEX "unique_username_not_deleted" ON "customers" ("username") WHERE "deleted_at" IS NULL`,
      `CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "customerId" uuid NOT NULL, "country" character varying NOT NULL, "city" character varying NOT NULL, "street" character varying NOT NULL, "detail" character varying NOT NULL, "phoneNumber" character varying NOT NULL, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`,
      `CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "customerId" uuid NOT NULL, "paymentId" uuid, "addressId" uuid NOT NULL, "productAmount" integer NOT NULL, "deliveryAmount" integer NOT NULL, "status" character varying NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`,
      `CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "orderId" uuid NOT NULL, "productId" uuid NOT NULL, "quantity" integer NOT NULL, "unitPrice" numeric(12,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`,
      `CREATE TABLE "company_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, CONSTRAINT "UQ_0803f913d81c696ac2832f51d5d" UNIQUE ("username"), CONSTRAINT "UQ_c6f15bbc68300ad13c9536da486" UNIQUE ("email"), CONSTRAINT "PK_fcd31773e604355d8a473de888c" PRIMARY KEY ("id"))`,
      `CREATE TABLE "company_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "key" character varying NOT NULL, "value" character varying, "image" character varying, CONSTRAINT "PK_36b605d66617cf62e4b3a0161dc" PRIMARY KEY ("id"))`,
      `CREATE UNIQUE INDEX "IDX_42779b850dfbe2fe419ddd8967" ON "company_details" ("key") WHERE "deleted_at" IS NULL`,
      `ALTER TABLE "product_filter_option_translations" ADD CONSTRAINT "FK_6ef7fc9894612c86f0483dd90c5" FOREIGN KEY ("productFilterOptionId") REFERENCES "product_filter_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      `ALTER TABLE "product_filter_options" ADD CONSTRAINT "FK_60d016ea173595107587b789db1" FOREIGN KEY ("productFilterId") REFERENCES "product_filters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      `ALTER TABLE "product_filter_translations" ADD CONSTRAINT "FK_8cf1ff195d463676c9ebbacdfc5" FOREIGN KEY ("productFilterId") REFERENCES "product_filters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      `ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "brand_translations" ADD CONSTRAINT "FK_71bbcded035051a8d3a6be97c3a" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      `ALTER TABLE "category_translations" ADD CONSTRAINT "FK_ce584bbf6422e668ff001e30cb0" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
      `ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "product_translations" ADD CONSTRAINT "FK_397d78efed9161e89701dbc125d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "addresses" ADD CONSTRAINT "FK_b5976584943ec93aa5394a55320" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_06a051324c76276ca2a9d1feb08" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_37636d260931dcf46d11892f614" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
      `ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    ];
    for (const statement of statements) await queryRunner.query(statement);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    if (process.env.ALLOW_BASELINE_DOWN !== 'true') {
      throw new Error(
        'InitialSchema down is destructive and requires ALLOW_BASELINE_DOWN=true on a disposable database',
      );
    }
    for (const table of [...this.coreTables].reverse()) {
      await queryRunner.query(`DROP TABLE IF EXISTS "${table}" CASCADE`);
    }
  }
}
